### ISSUE TITLE
Paging in a docx or xlsx report

### ISSUE THREAD

**Issue by hakankb** [cuba-platform/yarg#20]
Hi

I want to create a master detail report such that in every page 30 lines of detail records will be placed whereas master record will be repeated in each page. How can i do it with YARG ?

Regards

**Comment by tinhol** [comment]
Hello.
Have you tried to use page break in the master row?

**Comment by hakankb** [comment]
Well, a master may have hundreds of detail records. So a master may repeat in multiple pages where every page will contain (at most) 30 lines of detail. 

By the way, could you please explain how i can use page break in docx and xlsx.

**Comment by tinhol** [comment]
This kind of paging is not supported out-of-the box, but you can do it, manipulating with your bands.
About page breaks - there is a special object in xlsx and docx, and you can put it to the footer (separate band, printed after band with 30 rows)

**Comment by hakankb** [comment]
Hi

You say, "...About page breaks - there is a special object in xlsx and docx, and you can put it to the footer (separate band, printed after band with 30 rows)". 

I've tried to put a page break into footer band. but it didn't work. Could you please give an example ?

Thanks in advance

**Comment by tinhol** [comment]
Hello.
The row breaks in XLSX have been fixed. Please see the example in smoketest.XlsxSpecificTest#testXlsxRowBreaks.
The fix will be included to the upcoming release.

For the DOCX you can only add a page break with HTML (because nested bands are not yet supported in DOCX formatter). Please see the example in smoketest.DocxSpecificTest#testDocxWithColontitulesAndHtmlPageBreak.

Thank you for the feedback.
