### ISSUE TITLE
Not showing LOGO image when exporting from Docx template to HTML

### ISSUE THREAD

**Issue by srinivas460** [cuba-platform/yarg#22]
When i generate a Invoice using Docx template to html , everything is showing except the logo image ,
please help me to solve it

**Comment by tinhol** [comment]
Hello.

Base mechanism of convertaion from DOCX to HTML does not keep images loaded to the document. It will be fixed in future releases.

Though, for the next relase we are going to add ability to convert from DOCX to HTML with external Libre/Open Office server (as we do it with DOCX to PDF conversion). In case of using Libre/Open Office everything should work fine.

**Comment by andreysubbotin** [comment]
Fixed. See https://github.com/cuba-platform/yarg/commit/5de0ec686f8694759159a1aab0d2d0e71eb2e5d0

**Comment by srinivas460** [comment]
i tries with maven repository dependency, but i got  one jar Yarg-api-2.0.1.jar where i don't find the fixed classes. please help me to find solution
